# Generated by Django 5.1.5 on 2025-03-14 07:21

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Savol",
            fields=[
                ("title", models.TextField(max_length=255)),
                ("des", ckeditor.fields.RichTextField()),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("answer", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Usr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lvl", models.IntegerField(default=1)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
