# Generated by Django 5.1.5 on 2025-03-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('title', models.TextField(max_length=255)),
                ('des', models.TextField(max_length=255)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(max_length=255)),
                ('pas', models.TextField(max_length=255)),
                ('lvl', models.IntegerField(default=1)),
            ],
        ),
    ]
